### ISSUE TITLE
CIFAR-10 & CIFAR-100 ResNet Training

### ISSUE THREAD

**Issue by shaaaaron** [csm9493/L2UL#1]
Hello, thank you very much for providing the ResNet18 and ResNet50 checkpoints on CIFAR-10 and CIFAR-100!

However, when I wrote my own training code and retrained ResNet, I wasn't able to achieve the same results.

Could you please clarify whether your ResNet models were specifically trained on the CIFAR datasets, or did you use pre-trained models on ImageNet and then fine-tune them on CIFAR? Would it be possible for you to provide the training code or share the details of your training setup?

If you could assist, I would be very grateful!

**Comment by csm9493** [comment]
Sorry for the late reply. We didn't use a pretrained model on ImageNet. I attached the code that we used to train classifiers.
[train_models.zip](https://github.com/user-attachments/files/17181152/train_models.zip)

**Comment by shaaaaron** [comment]
Thank you so much for your response and for sharing the training code! I really appreciate your help.
